name: Terraform module to refresh
description: "Runs any terraform modules"
inputs:
  workingdir:
    description: Working Directory that terraform should execute commands
    required: true
  file:
    required: true
    description: Input file to output the enabled layers and file path
outputs:
  metadata_layers: ${{ steps.layers.outputs.metadata_layers }}
  datadog_layers: ${{ steps.layers.outputs.datadog_layers }}
  baseline_layers: ${{ steps.layers.outputs.baseline_layers }}
  networking_layers: ${{ steps.layers.outputs.networking_layers }}
  tableau_layers: ${{ steps.layers.outputs.tableau_layers }}
  abc_layers: ${{ steps.layers.outputs.abc_layers }}
  datalake_layers: ${{ steps.layers.outputs.datalake_layers }}    

runs:
  using: composite
  steps:
    - name: Execute scirpt to extract layers
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/sakula4/test-repo/main/scripts/resolveLayers.py -o resolveLayers.py
        chmod +x ${{ inputs.file }} resolveLayers.py
        python -u resolveLayers.py dev.json > test.txt
        cat test.txt
        cat test.txt >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT      
