name: Deploy Databricks

on: 
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        default: true
      environment:
        type: string
        default: dev

  repository_dispatch:
    types:
      - manual-trigger-mytest
      - manual-trigger-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.deploy == 'true' ? inputs.environment : "test"}}
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      # if: github.event.action == "YOUR_EVENT_TYPE"
      run: |
        echo "repository_dispatch triggered"