name: Deploy Databricks

on: 
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        default: true
      environment:
        type: string
        default: dev

  repository_dispatch:
    types:
      - manual-trigger-mytest
      - manual-trigger-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: "production"
    steps:
    - uses: actions/checkout@v1
    - name: step 1
      run: |
        echo "repository_dispatch triggered"

    - name: step2
      # if: github.event.action == "YOUR_EVENT_TYPE"
      run: |
        echo "repository_dispatch triggered"

    - name: step 3
      # if: github.event.action == "YOUR_EVENT_TYPE"
      run: |
        echo "repository_dispatch triggered"        
